spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.142.140.122:3306/WealthTrack?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: ying
    password: WealthTrack@2023
  data:
    redis:
      host: localhost
      port: 6379

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true

wechat:
  appid: wxa23790957de8e4e4
  secret: 269bbf342fb270d8d4d316e52631c99f

mybatis:
  configuration:
    map-underscore-to-camel-case: true

app:
  x-ti-app-id: c7b8351b98674abc1e0ac5a5d3d2292a
  x-ti-secret-code: 4d4919e559d06b6a3221cc179ef9506a